### PR TITLE
Resolve merge conflicts for spanish translation PR

### PR DESCRIPTION
**Pull request by svartkanin**
This is the update to resolve the merge conflicts from master. 
I've updated the base.po file with the new texts and copied over all your current translations

### CODE REVIEW

**Comment by Torxed** [comment]
I think this has to be set to target [es-translation](https://github.com/erickisos/archinstall/tree/es-translation) instead of `master`.
As the branch `es-translation` is what goes into upstream. I'm not sure this is possible as an outside collaborator of a fork, but that might help erickisos a bit if possible :)

Btw AMAZING work on the translations, and thank you both for doing this!

**Comment by svartkanin** [comment]
Let me try to update that if it's possible

**Comment by svartkanin** [comment]
Okay I raised a PR to the es-translation branch instead now, but there are conflicts there ;) 
So I'll let @erickisos desice which one is more convenient

**Comment by Torxed** [comment]
Sounds good : ) Thank you!

**Comment by erickisos** [comment]
I will close this PR, the other one is already merged! Thank you folks

**Pull request closed without merging**
